services:
  prpll:
    image: ghcr.io/yanshiqwq/prpll_docker/prpll:latest
    network_mode: none
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./data:/opt/prpll/data
      - /etc/localtime:/etc/localtime:ro
    command: ["-dir", "/opt/prpll/data/"]

  autoprimenet:
    image: ghcr.io/yanshiqwq/prpll_docker/autoprimenet:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/opt/autoprimenet/data
    command: ["--prpll", "-w", "/opt/autoprimenet/data/", "-l", "prime.ini", "--watch", "--cert-work"]